using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using Abstracta.JmeterDsl.Core.Samplers;

namespace Abstracta.JmeterDsl.Http
{
    /// <summary>
    /// Allows to configure a JMeter HTTP sampler to make HTTP requests in a test plan.
    /// </summary>
    public class DslHttpSampler : BaseSampler
    {
        private readonly string _url;
        private string _method;
        private string _body;

        public DslHttpSampler(string name, string url)
            : base(name)
        {
            _url = url;
        }

        /// <summary>
        /// Specifies that the sampler should send an HTTP POST to defined URL.
        /// </summary>
        /// <param name="body">to include in HTTP POST request body.</param>
        /// <param name="contentType">to be sent as Content-Type header in HTTP POST request.</param>
        /// <returns>the sampler for further configuration or usage.</returns>
        public DslHttpSampler Post(string body, MediaTypeHeaderValue contentType) =>
            Method(HttpMethod.Post.Method)
                .ContentType(contentType)
                .Body(body);

        /// <summary>
        /// Specifies the HTTP method to be used in the HTTP request generated by the sampler.
        /// </summary>
        /// <param name="method">is the HTTP method to be used by the sampler.</param>
        /// <returns>the sampler for further configuration or usage.</returns>
        public DslHttpSampler Method(string method)
        {
            _method = method;
            return this;
        }

        /// <summary>
        /// Specifies the body to be sent in the HTTP request generated by the sampler.
        /// </summary>
        /// <param name="body">to be used as in the body of the HTTP request.</param>
        /// <returns>the sampler for further configuration or usage.</returns>
        public DslHttpSampler Body(string body)
        {
            _body = body;
            return this;
        }

        /// <summary>
        /// Allows to easily specify the Content-Type HTTP header to be used by the sampler.
        /// </summary>
        /// <param name="contentType">value to send as Content-Type header.</param>
        /// <returns>the sampler for further configuration or usage.</returns>
        public DslHttpSampler ContentType(MediaTypeHeaderValue contentType)
        {
            FindHeaders().ContentType(contentType);
            return this;
        }

        private HttpHeaders FindHeaders()
        {
            var ret = (from c in _children
                       where c is HttpHeaders
                       select (HttpHeaders)c).FirstOrDefault();
            if (ret == null)
            {
                ret = new HttpHeaders();
                _children.Add(ret);
            }
            return ret;
        }

        /// <summary>
        /// Specifies an HTTP header to be sent by the sampler.
        /// <br/>
        /// To specify multiple headers just invoke this method several times with the different header
        /// names and values.
        /// </summary>
        /// <param name="name">specifies name of the HTTP header.</param>
        /// <param name="value">specifies value of the HTTP header.</param>
        /// <returns>the sampler for further configuration or usage.</returns>
        public DslHttpSampler Header(string name, string value)
        {
            FindHeaders().Header(name, value);
            return this;
        }
    }
}
