name: run tests
on:
  push:
    tags-ignore:
      - "*"
    branches:
      - "**"
jobs:
  test:
    runs-on: ubuntu-latest
    concurrency: azure_test
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
          cache: maven
      - name: Install dependencies
        run: dotnet restore  
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        # avoid running tests in parallel since it may happen that two tests try to modify .jmeter-dsl directory
        run: dotnet test -m:1 --no-build --configuration Release --verbosity normal
        env:
          AZURE_CREDS: ${{ secrets.AZURE_CREDS }}
          BZ_TOKEN: ${{ secrets.BZ_TOKEN }}
