name: run tests
on:
  push:
    tags-ignore:
      - "*"
    branches:
      - "**"
jobs:
  test:
    runs-on: ubuntu-latest
    concurrency: azure_test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: deploy github pages
        run: .github/vuepress-deploy.sh
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
